# Generated by Django 4.1.1 on 2022-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_traning_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traning',
            name='status',
            field=models.CharField(choices=[('InActive', 'InActive'), ('InProcess', 'InProcess'), ('Complete', 'Complete')], max_length=50),
        ),
    ]
